name: Game
description: Add a game
title: My Game
labels:
  - submission
body:
  - type: input
    attributes:
      label: Game Title
    validations:
      required: true
  - type: input
    attributes:
      label: Link
      description: Link to your game
    validations:
      required: true
  - type: input
    attributes:
      label: Store Name
      description: The name of the store page where your game is available (e.g. itch.io, Steam, etc.)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Cover Image
      description: Remember it must be 16:9 or else it will be cropped to fit that aspect ratio.
    validations:
      required: true
  - type: input
    attributes:
      label: Description
      description: Short description of your game (120 characters max)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Upload up to 3 different screenshots of your game
    validations:
      required: false
  - type: textarea
    attributes:
      label: Developers
      description: List of all developers of the game (The social links are optional)
      placeholder: |
        Geri - https://x.com/G_of_Geri
        Name - Social
        Name
        ...
    validations:
      required: true
