name: ⬆️ Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup:
    uses: ./.github/workflows/setup-node.yml
    with:
      node-version: '18'

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Regenerate HTML File
        run: node scripts/generate-from-state.js

  deploy:
    needs: build
    uses: ./.github/workflows/pages-setup-and-deploy.yml